### ISSUE TITLE
[Docs] New format for test.yaml

### ISSUE THREAD

**Issue by anushkamittal20** [kyverno/website#395] opened 2021-11-25 13:59 UTC
**Is your feature request related to a problem? Please describe current state:**
 
We now support a new format for test.yaml files along with the older format.
I think we might need some documentation for that.

**Describe the solution you'd like:**

We might need to mention the new format [here](https://kyverno.io/docs/kyverno-cli/#test)

**Additional context**

[https://github.com/kyverno/kyverno/pull/2733](https://github.com/kyverno/kyverno/pull/2733)
---
**Contributor Resources**
- [Contributing Guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md)

**Comment by chipzoller** [comment] 2022-02-06 23:11
Duplicate of #426

**Closed by chipzoller** 2022-02-06 23:11 UTC
